### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by Piolivers** [neundex/AudioBasedImageDistortion#1]
Hey there! First of all, thanks for the awesome work.

I can't get past the loader on the downloaded pack when I run it in live preview mode (Brackets). What am I missing? Thanks.

**Comment by shehroz-weoveri** [comment]
> Hey there! First of all, thanks for the awesome work.
> 
> I can't get past the loader on the downloaded pack when I run it in live preview mode (Brackets). What am I missing? Thanks.

Facing the same issue

**Comment by neundex** [comment]
You need to run these demos in a live server. Not sure how live preview mode works in Brackets, but you can give it a go in [VS Code](https://code.visualstudio.com/) with the [Live Server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) extension.
